/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class Constants {
  /**
   * Breakpoint sm.
   */
  public static readonly BREAK_POINT_SM: string = 'sm';
  /**
   * Breakpoint md.
   */
  public static readonly BREAK_POINT_MD: string = 'md';
  /**
   * Breakpoint lg.
   */
  public static readonly BREAK_POINT_LG: string = 'lg';
  /**
   * Index content width.
   */
  public static readonly INDEX_CONTENT_WIDTH: string = '91.1%';
  /**
   * Content padding top size.
   */
  public static readonly PADDING_TOP_SMALL: number = 8;
  /**
   * Card title height.
   */
  public static readonly CARD_TITLE_HEIGHT: number = 20;
  /**
   * Index title height.
   */
  public static readonly INDEX_TITLE_HEIGHT: number = 40;
  /**
   * Full screen width.
   */
  public static readonly FULL_WIDTH: string = '100%';
  /**
   * Full screen height.
   */
  public static readonly FULL_HEIGHT: string = '100%';
  /**
   * Content height.
   */
  public static readonly CONTENT_HEIGHT: number = 300;
  /**
   * Sub tab bottom height.
   */
  public static readonly SUB_TAB_BOT_HEIGHT: number = 25;
  /**
   * Sub tab width.
   */
  public static readonly SUB_TAB_HEIGHT: number = 30;
  /**
   * Tab index0.
   */
  public static readonly TAB_INDEX_ZERO: number = 0;
  /**
   * Tab index1.
   */
  public static readonly TAB_INDEX_ONE: number = 1;
  /**
   * Tab index2.
   */
  public static readonly TAB_INDEX_TWO: number = 2;
  /**
   * Tab index3.
   */
  public static readonly TAB_INDEX_THREE: number = 3;
  /**
   * More image width.
   */
  public static readonly MORE_IMAGE_WIDTH: number = 20;
  /**
   * Icon offset.
   */
  public static readonly ICON_OFFSET: number = -3;
  /**
   * Animation duration.
   */
  public static readonly ANIMATION_DURATION: number = 300;
  /**
   * Divider strokeWidth.
   */
  public static readonly STROKE_WIDTH: number = 2;
  /**
   * fontWeight.
   */
  public static readonly FONT_WEIGHT_TAB: number = 600;
  /**
   * TopTabData.
   */

}