/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class TabContentConstants {
  /**
   * Tab toast duration.
   */
  public static readonly TAB_TOAST_DURATION: number = 300;
  /**
   * Tab interval number.
   */
  public static readonly TAB_INTERVAL_NUMBER: number = 30;
  /**
   * Tab z_index.
   */
  public static readonly TAB_Z_INDEX: number = 2;
  /**
   * Tab tabs duration.
   */
  public static readonly TAB_TABS_DURATION: number = 100;
  /**
   * Tab opacity.
   */
  public static readonly TAB_OPACITY: number = 0.5;
  /**
   * Tab text opacity.
   */
  public static readonly TAB_TEXT_OPACITY: number = 0.7;
  /**
   * Tab text translate.
   */
  public static readonly TAB_TEXT_TRANSLATE: number = 0;
  /**
   * Tab text touch translate.
   */
  public static readonly TAB_TEXT_TOUCH_TRANSLATE: number = -15;
  /**
   * Tab text three margin top.
   */
  public static readonly TAB_TEXT_THREE_MARGIN_TOP: number = -4;
  /**
   * Tab text three margin left.
   */
  public static readonly TAB_TEXT_THREE_MARGIN_LEFT: number = -10;
  /**
   * Tab zero.
   */
  public static readonly TAB_ZERO: number = 0;
  /**
   * Tab one.
   */
  public static readonly TAB_ONE: number = 1;
  /**
   * Tab two.
   */
  public static readonly TAB_TWO: number = 2;
  /**
   * Tab ten.
   */
  public static readonly TAB_TEN: number = 10;
  /**
   * Tab duration.
   */
  public static readonly TAB_DURATION: number = 200;
  /**
   * Tab head image border radius.
   */
  public static readonly TAB_HEAD_IMAGE_BORDER_RADIUS: number = 22.5;
  /**
   * Tab head image margin left.
   */
  public static readonly TAB_HEAD_IMAGE_MARGIN_LEFT: number = 7.5;
  /**
   * Tab max line.
   */
  public static readonly TAB_MAX_LINE: number = 2;
  /**
   * Tab video.
   */
  public static readonly TAB_VIDEO: string = 'video';
  /**
   * Tab side.
   */
  public static readonly TAB_SIDE: string = 'side';
  /**
   * Tab video des.
   */
  public static readonly TAB_VIDEO_DES: string = 'videoDes';
  /**
   * Tab top view.
   */
  public static readonly TAB_TOP_VIEW: string = 'topView';
  /**
   * Tab playtime text id.
   */
  public static readonly TAB_PLAYTIME_TEXT_ID: string = 'playTimeText';
  /**
   * Tab total time text id.
   */
  public static readonly TAB_TOTAL_TIME_TEXT_ID: string = 'totalTimeText';
  /**
   * Tab text one id.
   */
  public static readonly TAB_TEXT_ONE_ID: string = 'text1';
  /**
   * Tab text two id.
   */
  public static readonly TAB_TEXT_TWO_ID: string = 'text2';
  /**
   * Tab text three id.
   */
  public static readonly TAB_TEXT_THREE_ID: string = 'text3';
  /**
   * Tab relative container.
   */
  public static readonly TAB_RELATIVE_CONTAINER: string = 'RelativeContainer';
  /**
   * Tab head image.
   */
  public static readonly TAB_HEAD_IMAGE: string = 'headImage';
  /**
   * Tab focus image.
   */
  public static readonly TAB_FOCUS_IMAGE: string = 'focusImage';
  /**
   * Tab like image.
   */
  public static readonly TAB_LIKE_IMAGE: string = 'likeImage';
  /**
   * Tab like image.
   */
  public static readonly TAB_LIKE_TEXT: string = 'likeText';
  /**
   * Tab comment image.
   */
  public static readonly TAB_COMMENT_IMAGE: string = 'commentImage';
  /**
   * Tab comment text.
   */
  public static readonly TAB_COMMENT_TEXT: string = 'commentText';
  /**
   * Tab favorite image.
   */
  public static readonly TAB_FAVORITE_IMAGE: string = 'favoriteImage';
  /**
   * Tab favorite text.
   */
  public static readonly TAB_FAVORITE_TEXT: string = 'favoriteText';
  /**
   * Tab share image.
   */
  public static readonly TAB_SHARE_IMAGE: string = 'shareImage';
  /**
   * Tab share text.
   */
  public static readonly TAB_SHARE_TEXT: string = 'shareText';
  /**
   * Tab name text.
   */
  public static readonly TAB_NAME_TEXT: string = 'nameText';
  /**
   * Tab description text.
   */
  public static readonly TAB_DESCRIPTION_TEXT: string = 'descriptionText';
  /**
   * Tab time text.
   */
  public static readonly TAB_TIME_TEXT: string = 'timeText';
  /**
   * Tab time text.
   */
  public static readonly TAB_GRAY_BACKGROUND: string = 'grayBackGround';
  /**
   * Tab hot image.
   */
  public static readonly TAB_HOT_IMAGE: string = 'hotImage';
  /**
   * Tab hot text.
   */
  public static readonly TAB_HOT_TEXT: string = 'hotText';
  /**
   * Tab hot spot.
   */
  public static readonly TAB_HOT_SPOT: string = 'hotSpot';
  /**
   * Tab people num arrow.
   */
  public static readonly TAB_PEOPLE_NUM_ARROW: string = 'peopleNumArrow';
  /**
   * Tab people num.
   */
  public static readonly TAB_PEOPLE_NUM: string = 'peopleNum';
  /**
   * Tab divider.
   */
  public static readonly TAB_DIVIDER: string = 'divider';
  /**
   * Tab search image.
   */
  public static readonly TAB_SEARCH_IMAGE: string = 'searchImage';
  /**
   * Tab follow text.
   */
  public static readonly TAB_FOLLOW_TEXT: string = 'followText';
  /**
   * Tab selected text.
   */
  public static readonly TAB_SELECTED_TEXT: string = 'selectedText';
  /**
   * Tab recommendation text.
   */
  public static readonly TAB_RECOMMENDATION_TEXT: string = 'recommendationText';
  /**
   * Tab screening hall text.
   */
  public static readonly TAB_SCREENING_HALL_TEXT: string = 'screeningHallText';
  /**
   * Tab top view divider.
   */
  public static readonly TAB_TOP_VIEW_DIVIDER: string = 'divider';
  /**
   * Tab add image.
   */
  public static readonly TAB_ADD_IMAGE: string = 'addImage';
  /**
   * Tabs.
   */
  public static readonly TAB_TABS: string = 'tabs';
  /**
   * Tab ber.
   */
  public static readonly TAB_TAB_BAR: string = 'tabBar';
  /**
   * Tab playtime text.
   */
  public static readonly TAB_PLAYTIME_TEXT: string = '00:';
  /**
   * Tab playtime text.
   */
  public static readonly TAB_TOTAL_TIME_TEXT: string = '/00:';
  /**
   * Tab container.
   */
  public static readonly TAB_CONTAINER: string = '__container__';
  /**
   * Tab image.
   */
  public static readonly TAB_IMAGE: string = 'image';
  /**
   * Tab video des time.
   */
  public static readonly TAB_VIDEO_DES_TIME: string = '2024-1-3 14:52';
  /**
   * Tab window stage.
   */
  public static readonly TAB_TIME_ZERO: string = '0';
  /**
   * Side video number.
   */
  public static readonly SIDE_NUMBER: number = 1234;
  /**
   * Tab array.
   */
  public static readonly TAB_ARRAY: string[] = [
    'app.string.tab_homepage',
    'app.string.tab_video',
    'app.string.tab_mall',
    'app.string.tab_mine'
  ];
  /**
   * Image array.
   */
  public static readonly IMAGE_ARRAY: string[] = [
    'app.media.tab_homepage',
    'app.media.tab_video',
    'app.media.tab_mall',
    'app.media.tab_mine'
  ];
}